import { Effect, Layer } from "effect";
import { defaultWrittenConfig } from "../domain/pre-release-state.ts";
import {
	ChangeWorkspaceInit,
	ChangeWorkspaceInitError,
} from "../services/ChangeWorkspaceInit.ts";
import { Filesystem } from "../services/Filesystem.ts";
import { encodePrettyJsonStringLine } from "./pure/json-codec.ts";

const changeReadme = `# Changes

Hello and welcome! This folder has been automatically generated by the changes CLI, a build tool that works
with multi-package repos, or single-package repos to help you version and publish your code. You can
find the full documentation for it [in the changes repository](https://github.com/jeremyc2/changes).

For usage and project docs, see [the changes repository](https://github.com/jeremyc2/changes).
`;

const make = Effect.gen(function* () {
	const filesystem = yield* Filesystem;

	const scaffold = Effect.fnUntraced(function* (rootDir: string) {
		const changeDir = `${rootDir}/.changes`;
		yield* filesystem.ensureDirectory(changeDir);
		const configPath = `${changeDir}/config.json`;
		const exists = yield* filesystem.exists(configPath);
		if (exists) {
			return yield* new ChangeWorkspaceInitError({
				message: "It looks like changes is already initialized",
			});
		}
		yield* filesystem.writeUtf8(
			configPath,
			encodePrettyJsonStringLine(defaultWrittenConfig),
		);
		yield* filesystem.writeUtf8(`${changeDir}/README.md`, changeReadme);
	});

	return ChangeWorkspaceInit.of({ scaffold });
});

export const layer = Layer.effect(ChangeWorkspaceInit, make);
